module.exports = {
  'extends': ['@metahub/eslint-config/es6-config'],
  'plugins': ['ava'],
  'rules': {
    'ava/assertion-arguments': 2,
    'ava/max-asserts': 0,
    'ava/no-async-fn-without-await': 2,
    'ava/no-cb-test': 2,
    'ava/no-duplicate-modifiers': 2,
    'ava/no-identical-title': 2,
    'ava/no-ignored-test-files': 2,
    'ava/no-invalid-end': 2,
    'ava/no-nested-tests': 2,
    'ava/no-only-test': 1,
    'ava/no-skip-assert': 1,
    'ava/no-skip-test': 1,
    'ava/no-statement-after-end': 2,
    'ava/no-todo-implementation': 1,
    'ava/no-todo-test': 'warn',
    'ava/no-unknown-modifiers': 2,
    'ava/prefer-async-await': 2,
    'ava/prefer-power-assert': 0,
    'ava/test-ended': 2,
    'ava/test-title': [2, 'always'],
    'ava/use-t-well': 2,
    'ava/use-t': 2,
    'ava/use-test': 2,
    'ava/use-true-false': 2
  }
}
